# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: gamescicd

on:
  push:
    branches: [ "ci-cd-dev" ]
  pull_request:
    branches: [ "ci-cd-dev" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: systemctl stop rsback -f
    - run: npm i
    - run: echo -e "PORTS=3004\nPORT=3003" > .env
    - run: rm vite.config.ts
    - run: mv /home/worker/_build/RsClone/RsClone/vite.config.ts.prod /home/worker/_build/RsClone/RsClone/vite.config.ts
    - run: npm run build
    - run: rm -rf /var/www/html/*
    - run: cp -rf /home/worker/_build/RsClone/RsClone/dist/* /var/www/html/
    - run: systemctl start rsback -f
